# Generated by Django 5.1 on 2025-05-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_downloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('description', models.TextField(help_text='Use <li> for bullet points. E.g., <li>Subject 1</li><li>Subject 2</li>')),
                ('order', models.IntegerField(help_text='Order in which this education should appear', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='e.g., App Dev, Data Science, Web Dev', max_length=50)),
                ('technologies', models.CharField(help_text='Comma-separated technologies, e.g., Python, Transformers API', max_length=200)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, help_text='Link to a live demo or more details (if applicable)', null=True)),
                ('order', models.IntegerField(help_text='Order in which this project should appear', unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.CharField(help_text='e.g., Dec 2024', max_length=50)),
                ('end_date', models.CharField(blank=True, help_text="e.g., Mar 2025 or 'Present'", max_length=50, null=True)),
                ('description', models.TextField(help_text='Use <li> for bullet points. E.g., <li>Task 1</li><li>Task 2</li>')),
                ('order', models.IntegerField(help_text='Order in which this experience should appear', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Work Experience',
                'ordering': ['order'],
            },
        ),
    ]
