# Generated by Django 5.1 on 2025-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_education_project_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter your achievement points using full HTML tags (e.g., <ul><li>Point 1</li><li>Point 2</li></ul>).')),
                ('order', models.IntegerField(help_text='Order in which this achievement block should appear (lower numbers first)', unique=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(help_text='e.g., App, Data, Web', max_length=50),
        ),
    ]
